x-health-check-defaults: &health_check_defaults
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 60s

services:
  home-proxy-webserver:
    image: ghcr.io/gitgc/home-proxy-webserver:main
    container_name: home-proxy-webserver
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    extra_hosts:
      - "nvr.coia.io:192.168.1.86"
      - "ha.internal.coia.io:192.168.1.228"
    environment:
      - CADDY_DOMAIN
      - CADDY_HEALTH_CHECK_URI
      - CF_AUTH_TOKEN
      - FRIGATE_UPSTREAM_HOST
      - HOME_ASSISTANT_UPSTREAM_HOST
      - UNIFI_UPSTREAM_HOST
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./config/proxy.caddy:/config/proxy.caddy:ro"
      - "./www:/var/www/html:ro"
      - "./data:/data"
    healthcheck:
      <<: *health_check_defaults
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "${CADDY_HEALTH_CHECK_URI}" ]
    labels:
      autoheal-app: true

  autoheal:
    image: willfarrell/autoheal:latest
    network_mode: none
    restart: unless-stopped
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal-app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
