services:
  home-proxy-webserver:
    image: ghcr.io/gitgc/home-proxy-webserver:main
    container_name: home-proxy-webserver
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    extra_hosts:
      - "nvr.coia.io:192.168.1.86"
      - "ha.internal.coia.io:192.168.1.228"
    environment:
      - CADDY_DOMAIN
      - CADDY_HEALTH_CHECK_URI
      - CF_AUTH_TOKEN
      - FRIGATE_UPSTREAM_HOST
      - HOME_ASSISTANT_UPSTREAM_HOST
      - UNIFI_UPSTREAM_HOST
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./config/proxy.caddy:/config/proxy.caddy:ro"
      - "./www:/var/www/html:ro"
      - "./data:/data"
    #healthcheck:
    #  test: [ "CMD", "wget", "--spider", "${CADDY_HEALTH_CHECK_URI}" ]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 5
    #  start_period: 60s
