x-health-check-defaults: &health_check_defaults
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 60s

services:
  caddy:
    image: ghcr.io/gitgc/home-proxy-webserver:main
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "nvr.coia.io:192.168.1.86"
      - "ha.internal.coia.io:192.168.1.228"
    environment:
      - CADDY_DOMAIN
      - CADDY_HEALTH_CHECK_URI
      - CF_AUTH_TOKEN
      - FRIGATE_UPSTREAM_HOST
      - HOME_ASSISTANT_UPSTREAM_HOST
      - UNIFI_UPSTREAM_HOST
      - PLEX_UPSTREAM_HOST
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./caddy/proxy.caddy:/config/proxy.caddy:ro"
      - "./www:/var/www/html:ro"
      - "./data:/data"
    healthcheck:
      <<: *health_check_defaults
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "${CADDY_HEALTH_CHECK_URI}" ]
    labels:
      autoheal-app: true

  webrtc-udp:
    image: alpine/socat:latest
    restart: unless-stopped
    command: UDP-LISTEN:8555,fork,reuseaddr UDP:192.168.1.86:8555
    ports:
      - 8555:8555/udp

  haproxy:
    image: haproxy:lts-alpine
    restart: unless-stopped
    ports:
      - 8554:8554/tcp
      - 8555:8555/tcp
    volumes:
      - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    healthcheck:
      <<: *health_check_defaults
      test: [ "CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg" ]
    labels:
      autoheal-app: true

  cockpit:
    image: cockpit/ws:latest
    expose:
      - "9090"
    # Needs access to the underlying host
    privileged: true
    pid: "host"
    environment:
      - CADDY_DOMAIN
      - VIRTUAL_HOST=edge.${CADDY_DOMAIN}
      - VIRTUAL_PORT=9090
      - CERT_NAME=default
    volumes:
      - "/:/host"

  autoheal:
    image: willfarrell/autoheal:latest
    network_mode: none
    restart: unless-stopped
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal-app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
