services:
  home-proxy-webserver:
    image: ghcr.io/gitgc/home-proxy-webserver:main
    container_name: home-proxy-webserver
    restart: unless-stopped
    network_mode: host
    init: true
    environment:
      - CADDY_DOMAIN
      - CADDY_HEALTH_CHECK_URI
      - CADDY_ADMIN
      - DO_AUTH_TOKEN
      - FRIGATE_UPSTREAM_HOST
      - SCRYPTED_UPSTREAM_HOST
      - HOME_ASSISTANT_UPSTREAM_HOST
      - UNIFI_UPSTREAM_HOST
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - JWT_SHARED_KEY
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./www:/var/www/html:ro"
      - "./data:/data"
      - "./config:/config"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "${CADDY_HEALTH_CHECK_URI}" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      - frigate

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_SCHEDULE
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
